<?php

use Magento\Framework\Escaper;
use Amasty\MWishlist\Block\Account\Wishlist\Item\Column\Move;

/**
 * @var Escaper $escaper
 * @var Move $block
 */
?>

<li @click="moveSingleItem(<?= $this->getItem()->getId() ?>)" class="amwishlist-item">
    <a class="amwishlist-button -clear"
       title="<?= $escaper->escapeHtmlAttr(__('Move Item')) ?>"
       data-mwishlist-ajax='<?= /** @noEscape */ $block->getPostData() ?>'
       data-amwishlist-js="item-move">
        <?= $escaper->escapeHtml(__('Move')) ?>
    </a>
</li>
