<?php

use Magento\Framework\Escaper;
use Amasty\MWishlist\Block\Account\Wishlist\Item\Column\Remove;

/**
 * @var Escaper $escaper
 * @var Remove $block
 */
?>

<li @click="deleteSingleItem(<?= $this->getItem()->getId() ?>)" class="amwishlist-item -error">
    <a class="amwishlist-button -clear"
       title="<?= $escaper->escapeHtmlAttr(__('Delete Item')) ?>"
       data-mwishlist-ajax='<?= /** @noEscape */ $block->getPostData() ?>'
       data-amwishlist-js="item-remove">
        <?= $escaper->escapeHtml(__('Delete')) ?>
    </a>
</li>
