<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var PasswordForm $block
 * @var Escaper $escaper
 */
?>

<div id="password-popup">
    <form class="form form-password"
          action="<?= $escaper->escapeUrl($block->getPostActionUrl()) ?>"
          method="post"
          id="login-form"
          data-mage-init='{"validation":{}}'>
        <div class="popup-title"><?= $escaper->escapeHtml(__('Submit a password to check page content.')) ?></div>
        <?= $block->getBlockHtml('formkey') ?>
        <fieldset class="fieldset login" data-hasrequired="<?= $escaper->escapeHtml(__('* Required Fields')) ?>">
            <div class="field password required">
                <label for="pass" class="label"><span><?= $escaper->escapeHtml(__('Password')) ?></span></label>
                <div class="control">
                    <input name="password" type="password" autocomplete="off"
                           class="input-text" id="pass"
                           title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>"
                           data-validate="{required:true}">
                </div>
            </div>
            <div class="field choice" data-bind="scope: 'showPassword'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action primary" name="send" id="send2">
                        <span><?= $escaper->escapeHtml(__('Submit')) ?></span></button>
                </div>
            </div>
        </fieldset>
    </form>
</div>

<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "showPassword": {
                            "component": "Magento_Customer/js/show-password",
                            "passwordSelector": "#pass"
                        }
                    }
                }
            }
        }
</script>

<script type="text/javascript">

    require([
        "jquery",
        'Magento_Ui/js/modal/modal',
        "domReady!"
    ], function ($, modal) {
        $('#password-popup').modal({
            autoOpen: false,
            clickableOverlay: false,
            innerScroll: false,
            modalClass: "password-popup-modal",
            responsive: true,
            type: 'popup',
            buttons: [],
            opened: function() {
                $('.password-popup-modal .modal-header button.action-close').remove()
            },
            closed: function() {}

        });
        $('#password-popup').modal('openModal');
    });
</script>


